export const hsClasses = [
    { name: 'DEATHKNIGHT', label: 'Death Knight', color: '#11707B' },
    { name: 'DRUID', label: 'Druid', color: '#703606' },
    { name: 'HUNTER', label: 'Hunter', color: '#016E01' },
    { name: 'MAGE', label: 'Mage', color: '#0092AB' },
    { name: 'PALADIN', label: 'Paladin', color: '#AA8F00' },
    { name: 'PRIEST', label: 'Priest', color: '#C7C19F' },
    { name: 'ROGUE', label: 'Rogue', color: '#4C4D48' },
    { name: 'SHAMAN', label: 'Shaman', color: '#0070DE' },
    { name: 'WARLOCK', label: 'Warlock', color: '#7624AD' },
    { name: 'WARRIOR', label: 'Warrior', color: '#8E1002' },
    { name: 'DEMONHUNTER', label: 'Demon Hunter', color: '#A330C9' },
    { name: 'NEUTRAL', label: 'Neutral', color: '#6c757d' }
];

export const hsSets = [
    { name: "EXPERT1", label: "Expert/Classic"},
    { name: "NAXX", label: "Curse of Naxxramas" },
    { name: "GVG", label: "Goblins vs Gnomes" },
    { name: "BRM", label: "Blackrock Mountain" },
    { name: "TGT", label: "The Grand Tournament" },
    { name: "LOE", label: "The League of Explorers" },
    { name: "OG", label: "Whispers of the Old Gods" },
    { name: "KARA", label: "One Night in Karazhan" },
    { name: "GANGS", label: "Mean Streets of Gadgetzan" },
    { name: "UNGORO", label: "Journey to Un'Goro" },
    { name: "ICECROWN", label: "Knights of the Frozen Throne" },
    { name: "LOOTAPALOOZA", label: "Kobolds & Catacombs" },
    { name: "GILNEAS", label: "The Witchwood" },
    { name: "BOOMSDAY", label: "The Boomsday Project" },
    { name: "TROLL", label: "Rastakhan's Rumble" },
    { name: "DALARAN", label: "Rise of Shadows" },
    { name: "ULDUM", label: "Saviours of Uldum" },
    { name: "DRAGONS", label: "Descent of Dragons" },
    { name: "YEAR_OF_THE_DRAGON", label: "Descent of Dragons 2?" },
    { name: "BLACK_TEMPLE", label: "Ashes of Outlands" },
    { name: "SCHOLOMANCE", label: "Scholomance Academy" },
    { name: "DEMON_HUNTER_INITIATE", label: "WHAT IS THIS?" },
    { name: "DARKMOON_FAIRE", label: "Madness at the Darkmoon Faire" },
    { name: "THE_BARRENS", label: "Forged in the Barrens" },
    { name: "STORMWIND", label: "United in Stormwind" },
    { name: "ALTERAC_VALLEY", label: "Fractured in Alterac Valley" },
    // { name: "LEGACY", label: "" },
    { name: "CORE", label: "Core Set" },
    // { name: "VANILLA", label: "" },
    { name: "THE_SUNKEN_CITY", label: "Voyage to the Sunken City" },
    { name: "REVENDRETH", label: "Murder at Castle Nathria" },
    { name: "RETURN_OF_THE_LICH_KING", label: "March of the Lich King" },
    { name: "PATH_OF_ARTHAS", label: "Path of Arthas" },
    { name: "BATTLE_OF_THE_BANDS", label: "Festival of Legends" },
    { name: "TITANS", label: "" },
];

export const hsRarity = [
    { name: "FREE", label: "Free" },
    { name: "COMMON", label: "Common" },
    { name: "RARE", label: "Rare" },
    { name: "EPIC", label: "Epic" },
    { name: "LEGENDARY", label: "Legendary" }
];